# Generated by Django 3.1.3 on 2021-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210117_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='author',
            field=models.BooleanField(default=False),
        ),
    ]
