# Generated by Django 3.1.3 on 2021-01-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='description',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='subtitle',
            field=models.BooleanField(default=False),
        ),
    ]
