# Generated by Django 3.1.3 on 2021-01-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210118_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='genre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
