# Generated by Django 3.1.3 on 2021-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210119_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
